def onerror(error):
    raise Exception(error)
